listen_addresses = '*'
max_connections = 40
shared_buffers = 96MB
work_mem = 2MB
maintenance_work_mem = 32MB
effective_cache_size = 256MB
checkpoint_timeout = 10min
checkpoint_completion_target = 0.9
wal_compression = on
random_page_cost = 1.1
log_min_duration_statement = 1000
log_connections = on
log_disconnections = on
