FROM node:26.8-alpine@sha256:ef24c5053d50fdc3e4e56eb4e7ddb7861874ab0fdc797046ba897581deb8e868

WORKDIR /app
COPY payment-server/package.json payment-server/package-lock.json ./
RUN npm ci
COPY payment-server/ .
RUN chown -R node:node /app

USER node
EXPOSE 3000
CMD ["npm", "run", "start:dev"]
