FROM node:26.7.0-alpine@sha256:aadf416b2cdce311a8811ba3f0608a61b77dbf997500e2eafe781b51f6a0b019

WORKDIR /app
COPY payment-server/package.json payment-server/package-lock.json ./
RUN npm ci
COPY payment-server/ .
RUN chown -R node:node /app

USER node
EXPOSE 3000
CMD ["npm", "run", "start:dev"]
