upstream crm_pool {
    least_conn;
    server crm-api:9000 max_fails=2 fail_timeout=10s;
}

upstream payment_pool {
    least_conn;
    server payment-api:3000 max_fails=2 fail_timeout=10s;
}

upstream dashboard_pool {
    least_conn;
    server dashboard:5173 max_fails=2 fail_timeout=10s;
}
