upstream crm_pool {
    zone crm_pool 64k;
    least_conn;
    server crm-api-1:9000 resolve max_fails=2 fail_timeout=10s;
    server crm-api-2:9000 resolve max_fails=2 fail_timeout=10s;
}

upstream payment_pool {
    zone payment_pool 64k;
    least_conn;
    server payment-api-1:3000 resolve max_fails=2 fail_timeout=10s;
    server payment-api-2:3000 resolve max_fails=2 fail_timeout=10s;
}

upstream dashboard_pool {
    zone dashboard_pool 64k;
    least_conn;
    server dashboard-1:8080 resolve max_fails=2 fail_timeout=10s;
    server dashboard-2:8080 resolve max_fails=2 fail_timeout=10s;
}
